/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as ProductsAddIndexRouteImport } from './routes/products/add/index'
import { Route as ProductsChar91idChar93IndexRouteImport } from './routes/products/[$id]/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAddIndexRoute = ProductsAddIndexRouteImport.update({
  id: '/products/add/',
  path: '/products/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsChar91idChar93IndexRoute =
  ProductsChar91idChar93IndexRouteImport.update({
    id: '/products/$id/',
    path: '/products/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart/': typeof CartIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$id/': typeof ProductsChar91idChar93IndexRoute
  '/products/add/': typeof ProductsAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartIndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/$id': typeof ProductsChar91idChar93IndexRoute
  '/products/add': typeof ProductsAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart/': typeof CartIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$id/': typeof ProductsChar91idChar93IndexRoute
  '/products/add/': typeof ProductsAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cart/' | '/products/' | '/products/$id/' | '/products/add/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cart' | '/products' | '/products/$id' | '/products/add'
  id:
    | '__root__'
    | '/'
    | '/cart/'
    | '/products/'
    | '/products/$id/'
    | '/products/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartIndexRoute: typeof CartIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsChar91idChar93IndexRoute: typeof ProductsChar91idChar93IndexRoute
  ProductsAddIndexRoute: typeof ProductsAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/add/': {
      id: '/products/add/'
      path: '/products/add'
      fullPath: '/products/add/'
      preLoaderRoute: typeof ProductsAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id/': {
      id: '/products/$id/'
      path: '/products/$id'
      fullPath: '/products/$id/'
      preLoaderRoute: typeof ProductsChar91idChar93IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartIndexRoute: CartIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsChar91idChar93IndexRoute: ProductsChar91idChar93IndexRoute,
  ProductsAddIndexRoute: ProductsAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
